import React from 'react';
import {
  Sword,
  Swords,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Wand2,
  Skull,
  Ghost,
  Flame,
  FlameKindling,
  Zap,
  CloudRain,
  CloudLightning,
  CloudSnow,
  Wind,
  Trees,
  Waves,
  Beer,
  Wine,
  Coins,
  Key,
  Scroll,
  BookOpen,
  Crown,
  Dices,
  Bell,
  Axe,
  Hammer,
  Crosshair,
  Target,
  Bomb,
  Footprints,
  Eye,
  Feather,
  Gem,
  Tent,
  Mountain,
  Droplets,
  Utensils,
  DoorOpen,
  Hourglass,
  Clock,
  Bug,
  Cat,
  Bird,
  Fish,
  Rat,
  Bone,
  Biohazard,
  HeartPulse,
  AlertTriangle,
  Music,
  Volume2,
  Disc,
  AudioLines,
  Radio,
  Compass,
  MapPin,
  Lock,
  Unlock,
  Moon,
  Sun,
  Activity,
  LucideIcon
} from 'lucide-react';

export interface IconCategoryGroup {
  name: string;
  icons: { name: string; label: string }[];
}

export const ICON_CATEGORIES: IconCategoryGroup[] = [
  {
    name: 'Combat & Weapons',
    icons: [
      { name: 'Sword', label: 'Sword' },
      { name: 'Swords', label: 'Dual Swords' },
      { name: 'Axe', label: 'Battleaxe' },
      { name: 'Hammer', label: 'Warhammer' },
      { name: 'Shield', label: 'Shield' },
      { name: 'ShieldAlert', label: 'Defend / Block' },
      { name: 'ShieldCheck', label: 'Armor Protection' },
      { name: 'Crosshair', label: 'Archery / Aim' },
      { name: 'Target', label: 'Bullseye' },
      { name: 'Bomb', label: 'Explosion / Bomb' },
      { name: 'Skull', label: 'Death / Critical' },
      { name: 'Bone', label: 'Bone / Skeleton' },
    ],
  },
  {
    name: 'Magic & Spells',
    icons: [
      { name: 'Wand2', label: 'Magic Wand' },
      { name: 'Sparkles', label: 'Arcane Magic' },
      { name: 'Zap', label: 'Lightning Spell' },
      { name: 'Flame', label: 'Fireball / Fire' },
      { name: 'FlameKindling', label: 'Campfire Magic' },
      { name: 'Ghost', label: 'Illusion / Spirit' },
      { name: 'Eye', label: 'Divination / Perception' },
      { name: 'Moon', label: 'Lunar / Darkness' },
      { name: 'Sun', label: 'Radiant / Dawn' },
      { name: 'Gem', label: 'Spell Gem' },
      { name: 'Scroll', label: 'Spell Scroll' },
      { name: 'BookOpen', label: 'Grimoire' },
    ],
  },
  {
    name: 'Ambience & Nature',
    icons: [
      { name: 'CloudRain', label: 'Rain / Storm' },
      { name: 'CloudLightning', label: 'Thunder' },
      { name: 'CloudSnow', label: 'Blizzard / Ice' },
      { name: 'Wind', label: 'Howling Wind' },
      { name: 'Waves', label: 'Ocean Waves' },
      { name: 'Droplets', label: 'Water Drips' },
      { name: 'Trees', label: 'Forest / Woods' },
      { name: 'Mountain', label: 'Mountain / Cave' },
      { name: 'Tent', label: 'Campsite' },
      { name: 'Compass', label: 'Wilderness' },
      { name: 'MapPin', label: 'Dungeon Room' },
    ],
  },
  {
    name: 'Tavern & Adventure',
    icons: [
      { name: 'Beer', label: 'Ale / Tavern' },
      { name: 'Wine', label: 'Banquet' },
      { name: 'Utensils', label: 'Feast' },
      { name: 'Dices', label: 'Dice Roll' },
      { name: 'Coins', label: 'Gold / Loot' },
      { name: 'Crown', label: 'Royalty / King' },
      { name: 'Key', label: 'Key / Chest' },
      { name: 'Lock', label: 'Locked Door' },
      { name: 'Unlock', label: 'Lockpick' },
      { name: 'DoorOpen', label: 'Creaky Door' },
      { name: 'Footprints', label: 'Sneak / Stealth' },
      { name: 'Bell', label: 'Alarm Bell' },
      { name: 'Hourglass', label: 'Time Running Out' },
      { name: 'Clock', label: 'Church Bells' },
    ],
  },
  {
    name: 'Monsters & Danger',
    icons: [
      { name: 'Bug', label: 'Spider / Swarm' },
      { name: 'Rat', label: 'Dungeon Rat' },
      { name: 'Cat', label: 'Beast / Feline' },
      { name: 'Bird', label: 'Raven / Griffin' },
      { name: 'Fish', label: 'Sea Monster' },
      { name: 'AlertTriangle', label: 'Trap / Danger' },
      { name: 'Biohazard', label: 'Poison / Acid' },
      { name: 'HeartPulse', label: 'Heartbeat / Tension' },
      { name: 'Activity', label: 'Combat Pulse' },
    ],
  },
  {
    name: 'Music & Audio',
    icons: [
      { name: 'Music', label: 'BGM / Melody' },
      { name: 'AudioLines', label: 'Sound Waves' },
      { name: 'Volume2', label: 'SFX' },
      { name: 'Disc', label: 'Lute / Bard Song' },
      { name: 'Radio', label: 'Broadcast' },
      { name: 'Feather', label: 'Gentle Melody' },
    ],
  },
];

export const ICON_MAP: Record<string, LucideIcon> = {
  Sword,
  Swords,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Wand2,
  Skull,
  Ghost,
  Flame,
  FlameKindling,
  Zap,
  CloudRain,
  CloudLightning,
  CloudSnow,
  Wind,
  Trees,
  Waves,
  Beer,
  Wine,
  Coins,
  Key,
  Scroll,
  BookOpen,
  Crown,
  Dices,
  Bell,
  Axe,
  Hammer,
  Crosshair,
  Target,
  Bomb,
  Footprints,
  Eye,
  Feather,
  Gem,
  Tent,
  Mountain,
  Droplets,
  Utensils,
  DoorOpen,
  Hourglass,
  Clock,
  Bug,
  Cat,
  Bird,
  Fish,
  Rat,
  Bone,
  Biohazard,
  HeartPulse,
  AlertTriangle,
  Music,
  Volume2,
  Disc,
  AudioLines,
  Radio,
  Compass,
  MapPin,
  Lock,
  Unlock,
  Moon,
  Sun,
  Activity,
};

interface SoundIconProps {
  name: string;
  className?: string;
  size?: number;
}

export const SoundIcon: React.FC<SoundIconProps> = ({ name, className = 'w-5 h-5', size }) => {
  const IconComponent = ICON_MAP[name] || Volume2;
  return <IconComponent className={className} size={size} />;
};
